# Домашняя работа Семинар 1

In [1]:
import numpy as np
from math import factorial as fc
from fractions import Fraction

Добавлю функции нахождения количества сочетаний, размещений и перестановок

In [11]:
def c (k,n): # сочетание
    return (fc(n) // (fc(k)*fc(n-k)))

def cf (k,n): # сочетание с неправильной дробью
    return Fraction(fc(n) // (fc(k)*fc(n-k)))

def a (k,n): # размещение
    return (fc(n) // fc(n-k))

def af (k,n): # размещение с неправильной дробью
    return Fraction(fc(n) // fc(n-k))

def p (n): # перестановка
    return fc(n)

## Задание 1<br>
Из колоды в $52$ карты извлекаются случайным образом $4$ карты.<br>
a) Найти вероятность того, что все карты – крести.<br> 
б) Найти вероятность, что среди $4$-х карт окажется хотя бы один туз.

Решим часть а:<br>

Для того, чтобы найти вероятность нужно применить формулу:<br>

$P=\dfrac{число\: исходов,\: благоприятствующих\: событию}{общее\: число\: исходов}$<br>

Сначала найдем число благоприятных исходов:<br>

Всего в колоде $13$ крестей, значит нам нужно найти сочетание $4$ из $13$<br>

$C_{13}^4=\dfrac{13!}{4!(13-4)!}=715$

In [12]:
c(4,13)

715

Теперь нам нужно найти общее число исходов $4$ из $52$ карт<br>

$C_{52}^4=\dfrac{52!}{4!\cdot (52-4)!}=\dfrac{52\cdot 51\cdot 50\cdot 49\cdot 48!}{24\cdot 48!}=270725$

In [13]:
c(4,52)

270725

Найдем вероятность<br>

$P=715/270725 \approx 0.0026$

In [14]:
round(715/270725, 4)

0.0026

Есть другой вариант решения, через умножение вероятностей:

$P = \dfrac{13}{52} \cdot \dfrac{12}{51} \cdot \dfrac{11}{50} \cdot \dfrac{10}{49} \approx 0.0026$

In [2]:
round((13/52)*(12/51)*(11/50)*(10/49), 4)

0.0026

### решим часть б:

Для того, чтобы посчитать вероятность того, что среди $4$-х карт окажется хотя бы один туз, мы можем посчитать вероятность для каждого варианта с $1$, $2$, $3$, $4$ тузами и сложить их по формуле полной вероятности или посчитать вероятность непопадания тузов в исход и вычесть его из единицы.

### Способ 1

Количество возможных комбинация из $1$ туза

$C_4^1=4$<br>
Количество возможных комбинация из $3$ нетузов

$C_{48}^3=\frac{48!}{3!\cdot 45!}=\frac{45!\cdot 46\cdot 47 \cdot 48}{6 \cdot 45!}=8 \cdot 46 \cdot 47 = 17296$<br>

Количество возможных комбинация из $2$ тузов

$C_4^2=6$<br>
Количество возможных комбинация из $2$ нетузов

$C_{48}^2=\frac{48!}{2\cdot 46!}=\frac{46!\cdot 47 \cdot 48}{2 \cdot 46!}=24 \cdot 47 = 1128$<br>

Количество возможных комбинация из $3$ тузов

$C_4^3=4$<br>
Количество возможных комбинация из $1$ нетуза

$C_{48}^1 = 48$<br>

Количество возможных комбинация из 4 тузов $C_4^4=1$<br>

Общее количество исходов  мы исчислили ранее $C_{52}^4 = 270725$

Итого вероятность того, что среди 4-х карт окажется хотя бы один туз будет равна:

$P(A)=\frac{4\cdot 17296 + 6 \cdot 1128 + 4 \cdot 48 + 1}{270725}=\frac{76145}{270725}\approx 0.2813$


In [38]:
print(c(1,4), c(3,48), c(2,4) , c(2,48), c(3,4) , c(1,48), c(4,4))
print((c(1,4) * c(3,48)) + (c(2,4) * c(2,48)) + (c(3,4) * c(1,48)) + c(4,4))
print(round(76145/270725, 4))

4 17296 6 1128 4 48 1
76145
0.2813


### Способ 2

Количество возможных комбинация из $4$ нетузов

$C_{48}^4=\frac{48!}{4!\cdot 44!}=\frac{44!\cdot 45\cdot 46\cdot 47 \cdot 48}{24 \cdot 44!}=2 \cdot 47 \cdot 46 \cdot 45 = 194580$<br>

Общее количество исходов  мы исчислили ранее $C_{52}^4 = 270725$

Итого искомая вероятность равна:

$\bar P = \frac{194580}{270725} \approx 0.7187 $

$P = 1 - \bar P = 1 - 0.7187 \approx 0.2813$




In [41]:
print(c(4,48))
print(round(194580/270725, 4))
print(1 - 0.7187)

194580
0.7187
0.2813


## Задание 2<br>
На входной двери подъезда установлен кодовый замок, содержащий десять кнопок с цифрами от $0$ до $9$. Код содержит три цифры, которые нужно нажать одновременно. Какова вероятность того, что человек, не знающий код, откроет дверь с первой попытки?

### Решение

В данном случае вероятность мы можем посчитать по формуле:

$P=\dfrac{m}{n}$,

$m=1$, так как код только один, 

$n$ это общее количество сочетаний:

$C_{10}^3=\dfrac{10!}{3!\cdot (10-3)!}=\dfrac{10\cdot 9\cdot 8 \cdot 7!}{2 \cdot 3\cdot 7!}= 10\cdot 4\cdot 3 = 120$

$P=\dfrac{m}{n}= \dfrac{1}{120} \approx 0.0083$

In [18]:
c(3,10)

120

In [20]:
round(1/120,4)

0.0083

Есть другой вариант

$P = \dfrac {3}{10} \cdot \dfrac {2}{9} \cdot \dfrac {1}{8} = \dfrac{1}{120} \approx 0.0083$

## Задание 3

В ящике имеется $15$ деталей, из которых $9$ окрашены. Рабочий случайным образом извлекает $3$ детали.<br> 
Какова вероятность того, что все извлеченные детали окрашены?

### Решение

$C_9^3$ - количество благоприятных исходов

$C_{15}^3$ - всего исходов

$P(A)=\dfrac{C_9^3}{C_{15}^3}=\dfrac{\dfrac{9!}{3!\cdot 6!}}{\dfrac{15!}{3! \cdot 12!}}= \dfrac{9! \cdot 3! \cdot 12!}{3! \cdot 6! \cdot 15!}= 12/65 \approx 0.1846$

In [26]:
print(cf(3,9))
print(cf(3,15))
print(cf(3,9)/cf(3,15))
print(round(float(c(3,9)/c(3,15)),4))

84
455
12/65
0.1846


Есть другой вариант

$P = \dfrac {9}{15} \cdot \dfrac {8}{14} \cdot \dfrac {7}{13} = \dfrac{12}{65} \approx 0.1846$

## Задание 4

В лотерее $100$ билетов. Из них $2$ выигрышных. Какова вероятность того, что $2$ приобретенных билета окажутся выигрышными?

### Решение

Удачный исход $C_2^2 = 1$

Всего исходов $C_{100}^2=\frac{100!}{2!\cdot 98!}=\frac{100\cdot 99}{2}= 4950$

Вероятность того, что $2$ приобретенных билета окажутся выигрышными равна

$\frac{1}{4950} \approx 0.0002$

In [31]:
print(c(2,100))
print(round(1/c(2,100),4))


4950
0.0002


Есть другой вариант

$P = \dfrac {2}{100} \cdot \dfrac {1}{99} = \dfrac{1}{99 * 50} \approx 0.0002$